App\Entity\Form:
  properties:
    name:
      - NotBlank: ~
      - Regex:
            pattern: '/^[a-z]+$/i'
            htmlPattern: '[a-zA-Z]+'
    surname:
      - NotBlank: ~
      - Regex:
          pattern: '/^[a-z]+$/i'
          htmlPattern: '[a-zA-Z]+'
    pesel:
      - NotBlank: ~
      - Length: 11
      - Regex:
          pattern: '/^[0-9]+$/i'


    email:
      - NotBlank: ~
    date:
      - NotBlank: ~
    sex:
      - NotBlank: ~
